insert into category(name) values ('Acceleration');
insert into category(name) values ('Acceleration - Angular');
insert into category(name) values ('Angle');
insert into category(name) values ('Area');
insert into category(name) values ('Astronomical');
insert into category(name) values ('Charge');
insert into category(name) values ('Clothing Size - Women');
insert into category(name) values ('Concentration - Molar');
insert into category(name) values ('Concentration - Solution');
insert into category(name) values ('Cooking');
insert into category(name) values ('Currency Exchange Rate');
insert into category(name) values ('Current');
insert into category(name) values ('Data Storage');
insert into category(name) values ('Density');
insert into category(name) values ('Efficiency - HVAC');
insert into category(name) values ('Electric Capacitance');
insert into category(name) values ('Electric Conductance');
insert into category(name) values ('Electric Conductivity');
insert into category(name) values ('Electric Field Strength');
insert into category(name) values ('Electric Potential');
insert into category(name) values ('Electric Resistance');
insert into category(name) values ('Electric Resistivity');
insert into category(name) values ('Energy / Work');
insert into category(name) values ('Energy Flux');
insert into category(name) values ('Enthalpy');
insert into category(name) values ('Entropy');
insert into category(name) values ('Flow - Mass');
insert into category(name) values ('Flow - Molar');
insert into category(name) values ('Flow - Volume');
insert into category(name) values ('Force');
insert into category(name) values ('Frequency - Wavelength');
insert into category(name) values ('Fuel Consumption');
insert into category(name) values ('Fuel Efficiency - Mass');
insert into category(name) values ('Fuel Efficiency - Volume');
insert into category(name) values ('Gas Constant');
insert into category(name) values ('Heat Capacity');
insert into category(name) values ('Heat Density');
insert into category(name) values ('Heat Flow Rate');
insert into category(name) values ('Heat Flux Density');
insert into category(name) values ('Heat Rate');
insert into category(name) values ('Heat Transfer Coefficient');
insert into category(name) values ('Henry''s Law');
insert into category(name) values ('Hex./Dec./Bin.');
insert into category(name) values ('Illumination');
insert into category(name) values ('Image Resolution');
insert into category(name) values ('Inductance');
insert into category(name) values ('Length / Distance');
insert into category(name) values ('Linear Charge Density');
insert into category(name) values ('Linear Current Density');
insert into category(name) values ('Lumber - Volume');
insert into category(name) values ('Luminance');
insert into category(name) values ('Luminous Intensity');
insert into category(name) values ('Magnetic Field Strength');
insert into category(name) values ('Magnetic Flux');
insert into category(name) values ('Magnetic Flux Density');
insert into category(name) values ('Magnetomotive Force');
insert into category(name) values ('Mass Flux Density');
insert into category(name) values ('Moment of Force');
insert into category(name) values ('Moment of Inertia');
insert into category(name) values ('Permeability');
insert into category(name) values ('Power');
insert into category(name) values ('Power Density');
insert into category(name) values ('Prefixes');
insert into category(name) values ('Pressure');
insert into category(name) values ('Radiation');
insert into category(name) values ('Radiation Absorbed Dose');
insert into category(name) values ('Radiation Activity');
insert into category(name) values ('Radiation Exposure');
insert into category(name) values ('Ring Size');
insert into category(name) values ('Shoe Size - Men');
insert into category(name) values ('Shoe Size - Women');
insert into category(name) values ('Sound');
insert into category(name) values ('Specific Heat');
insert into category(name) values ('Specific Power');
insert into category(name) values ('Specific Volume');
insert into category(name) values ('Steam Tables');
insert into category(name) values ('Surface Charge Density');
insert into category(name) values ('Surface Current Density');
insert into category(name) values ('Surface Tension');
insert into category(name) values ('Temperature');
insert into category(name) values ('Temperature Interval');
insert into category(name) values ('Thermal Conductivity');
insert into category(name) values ('Thermal Expansion');
insert into category(name) values ('Thermal Resistance');
insert into category(name) values ('Time');
insert into category(name) values ('TOEFL Scores');
insert into category(name) values ('Torque');
insert into category(name) values ('Typography');
insert into category(name) values ('Velocity');
insert into category(name) values ('Velocity - Angular');
insert into category(name) values ('Viscosity - Dynamic');
insert into category(name) values ('Viscosity - Kinematic');
insert into category(name) values ('Volume - Dry');
insert into category(name) values ('Volume / Capacity');
insert into category(name) values ('Volume Charge Density');
insert into category(name) values ('Weight / Mass');