insert into unit(categoryId, shortName, name, enabled) values (11, "AED", "United Arab Emirates dirham", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "AFN", "Afghan afghani", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ALL", "Albanian lek", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "AMD", "Armenian dram", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ANG", "Netherlands Antillean guilder", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "AOA", "Angolan kwanza", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ARS", "Argentine peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "AUD", "Australian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "AWG", "Aruban florin", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "AZN", "Azerbaijani manat", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BAM", "Bosnia and Herzegovina convertible mark", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BBD", "Barbadian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BDT", "Bangladeshi taka", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BGN", "Bulgarian lev", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BHD", "Bahraini dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BIF", "Burundian franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BMD", "Bermudian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BND", "Brunei dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BOB", "Bolivian boliviano", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BRL", "Brazilian real", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BSD", "Bahamian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BTN", "Bhutanese ngultrum", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BWP", "Botswana pula", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BYR", "Belarusian ruble", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "BZD", "Belize dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CAD", "Canadian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CDF", "Congolese franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CHF", "Swiss franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CLF", "Chilean Unidad de Fomento", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CLP", "Chilean peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CNH", "Chinese Offshore Yuan", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CNY", "Chinese yuan", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "COP", "Colombian peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "COPPER HIGHGRADE", "COPPER HIGHGRADE", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CRC", "Costa Rican colón", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CUP", "Cuban peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CVE", "Cape Verdean escudo", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "CZK", "Czech koruna", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "DJF", "Djiboutian franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "DKK", "Danish krone", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "DOP", "Dominican peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "DZD", "Algerian dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "EGP", "Egyptian pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ETB", "Ethiopian birr", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "EUR", "Euro", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "FJD", "Fijian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "FKP", "Falkland Islands pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GBP", "British pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GEL", "Georgian lari", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GHS", "Ghana cedi", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GIP", "Gibraltar pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GMD", "Gambian dalasi", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GNF", "Guinean franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GOLD 1 UZ", "GOLD 1 UZ", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GTQ", "Guatemalan quetzal", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "GYD", "Guyanese dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "HKD", "Hong Kong dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "HNL", "Honduran lempira", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "HRK", "Croatian kuna", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "HTG", "Haitian gourde", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "HUF", "Hungarian forint", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "IDR", "Indonesian rupiah", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "IEP", "Irish Pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ILS", "Israeli new shekel", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "INR", "Indian rupee", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "IQD", "Iraqi dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "IRR", "Iranian rial", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ISK", "Icelandic króna", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "JMD", "Jamaican dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "JOD", "Jordanian dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "JPY", "Japanese yen", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KES", "Kenyan shilling", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KGS", "Kyrgyzstani som", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KHR", "Cambodian riel", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KMF", "Comorian franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KPW", "North Korean won", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KRW", "South Korean won", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KWD", "Kuwaiti dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "KZT", "Kazakhstani tenge", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LAK", "Lao kip", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LBP", "Lebanese pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LKR", "Sri Lankan rupee", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LRD", "Liberian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LSL", "Lesotho loti", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LTL", "Lithuanian litas", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LVL", "Latvian lats", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "LYD", "Libyan dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MAD", "Moroccan dirham", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MDL", "Moldovan leu", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MGA", "Malagasy ariary", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MKD", "Macedonian denar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MMK", "Burmese kyat", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MNT", "Mongolian tögrög", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MOP", "Macanese pataca", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MRO", "Mauritanian ouguiya", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MUR", "Mauritian rupee", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MVR", "Maldivian rufiyaa", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MWK", "Malawian kwacha", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MXN", "Mexican peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MYR", "Malaysian ringgit", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "MZN", "Mozambican metical", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "NAD", "Namibian dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "NGN", "Nigerian naira", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "NIO", "Nicaraguan córdoba", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "NOK", "Norwegian krone", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "NPR", "Nepalese rupee", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "NZD", "New Zealand dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "OMR", "Omani rial", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PAB", "Panamanian balboa", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PALLADIUM 1 UZ", "PALLADIUM 1 UZ", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PEN", "Peruvian nuevo sol", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PGK", "Papua New Guinean kina", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PHP", "Philippine peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PKR", "Pakistani rupee", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PLATIN 1 UZ 999", "PLATIN 1 UZ 999", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PLN", "Polish złoty", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "PYG", "Paraguayan guaraní", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "QAR", "Qatari riyal", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "RON", "Romanian leu", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "RSD", "Serbian dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "RUB", "Russian ruble", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "RWF", "Rwandan franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SAR", "Saudi riyal", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SBD", "Solomon Islands dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SCR", "Seychellois rupee", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SDG", "Sudanese pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SEK", "Swedish krona", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SGD", "Singapore dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SHP", "Saint Helena pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SILVER 1 OZ 999 NY", "SILVER 1 OZ 999 NY", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SLL", "Sierra Leonean leone", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SOS", "Somali shilling", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SRD", "Surinamese dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "STD", "São Tomé and Príncipe dobra", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SVC", "Salvadoran colón", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SYP", "Syrian pound", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "SZL", "Swazi lilangeni", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "THB", "Thai baht", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TJS", "Tajikistani somoni", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TMT", "Turkmenistan manat", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TND", "Tunisian dinar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TOP", "Tongan paʻanga", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TRY", "Turkish lira", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TTD", "Trinidad and Tobago dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TWD", "New Taiwan dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "TZS", "Tanzanian shilling", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "UAH", "Ukrainian hryvnia", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "UGX", "Ugandan shilling", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "UYU", "Uruguayan peso", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "UZS", "Uzbekistani som", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "VEF", "Venezuelan bolívar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "VND", "Vietnamese đồng", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "VUV", "Vanuatu vatu", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "WST", "Samoan tālā", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "XAF", "Central African CFA franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "XCD", "East Caribbean dollar", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "XDR", "IMF Special Drawing", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "XOF", "West African CFA franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "XPF", "CFP franc", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "YER", "Yemeni rial", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ZAR", "South African rand", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ZMK", "Zambian kwacha", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ZMW", "Zambian", 1);
insert into unit(categoryId, shortName, name, enabled) values (11, "ZWL", "Zimbabwean dollar[N]", 1);
